"""added_table_webhook_delivery_states

Revision ID: 2
Revises: 1
Create Date: 2026-03-05 16:19:15.432443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2'
down_revision: Union[str, Sequence[str], None] = '1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_delivery_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.endpoint_id'], name=op.f('fk_webhook_delivery_states_endpoint_id_webhook_endpoints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['outbox_events.event_id'], name=op.f('fk_webhook_delivery_states_event_id_outbox_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_delivery_states')),
    sa.UniqueConstraint('event_id', 'endpoint_id', name='uq_webhook_delivery_states_event_endpoint')
    )
    op.create_index(op.f('ix_webhook_delivery_states_endpoint_id'), 'webhook_delivery_states', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_states_event_id'), 'webhook_delivery_states', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_states_status'), 'webhook_delivery_states', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_delivery_states_status'), table_name='webhook_delivery_states')
    op.drop_index(op.f('ix_webhook_delivery_states_event_id'), table_name='webhook_delivery_states')
    op.drop_index(op.f('ix_webhook_delivery_states_endpoint_id'), table_name='webhook_delivery_states')
    op.drop_table('webhook_delivery_states')
    # ### end Alembic commands ###
